import React from 'react'
import Head from 'next/head'

import Header from '@/components/navbar'
import Footer from '@/components/footer'
const Layout= ({children}) => {
  return (
   <div >
    <Head>
    <title>Movies App</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
    <div> 
<Header/>

    <main>
    {children} 
    </main>
    </div>
    <Footer/>
   </div>
  )
}

export default Layout
